name: luminate_flutter
description: Lily app for luminate demonstrations.

# The following line prevents the package from being accidentally published to
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

#Dependencies
dependencies:
  flutter:
    sdk: flutter
  #3rd party
  circular_countdown_timer: '^0.2.0'
  cupertino_icons: ^1.0.2
  lottie: ^1.1.0

#App Icon setup (scale altered for android): To recompile icon: "flutter pub run flutter_launcher_icons:main"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/Icons/app_icon_ios.jpg"
  image_path_android: "assets/Icons/app_icon_android.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/Icons/app_icon_android.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  #Import all assets in the following folders
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/animations/

  #Imported fonts
  fonts:
    #Sergoe UI font
    - family: sergoe_ui
      fonts:
        - asset: assets/fonts/segoe_ui.ttf
    #Gilroy regular
    - family: gilroy
      fonts:
        - asset: assets/fonts/gilroy_regular.ttf
    #Sofia Pro Soft
    - family: sofia
      fonts:
          - asset: assets/fonts/sofia_pro_soft_medium.ttf
